# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{glapp}
  s.version = "0.0.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Tom Lieber}]
  s.date = %q{2012-04-29}
  s.email = %q{tom@alltom.com}
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    "README.textile",
    "Rakefile",
    "VERSION",
    "examples/hedgehog.ppm",
    "examples/sprite.rb",
    "examples/triangles.rb",
    "examples/triangles2.rb",
    "glapp.gemspec",
    "lib/glapp.rb"
  ]
  s.homepage = %q{http://github.com/alltom/glapp}
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.5}
  s.summary = %q{ruby-opengl wrapper for writing quick applets}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<opengl>, [">= 0.7.0.pre1"])
    else
      s.add_dependency(%q<opengl>, [">= 0.7.0.pre1"])
    end
  else
    s.add_dependency(%q<opengl>, [">= 0.7.0.pre1"])
  end
end

